FORMAT: 1A
HOST: https://portal.vn.teslamotors.com

# Tesla Model S REST API
This is unofficial documentation of the Tesla Model S REST API used by the iOS and Android apps. It features functionality to monitor and control the Model S remotely. 

# Group Authentication Flow
These endpoints handle login and session management
## GET /login
Returns the login form. Sets a _s_portal_session cookie for the session
+ Response 200

    + Headers
        
            Set-Cookie: _s_portal_session={cookie}; path=/; secure; HttpOnly
            
    + Body
    
            Login Screen HTML
            
## POST /login
Performs the login. Takes in an plain text email and password, matching the owner's login from [http://teslamotors.com/mytesla](http://teslamotors.com/mytesla).

Sets a *user_credentials* cookie that expires in 3 months, which is passed along with all future requests to authenticate the user.

Redirects back to a dummy welcome page. This page is ignored by the smartphone app and can be ignored by your API client.
+ Request (application/x-www-form-urlencoded)

    + Parameters
    
        + user_session[email] (string, "me@me.me") ... The email address for the owner's Tesla account
        + user_session[password] (string, "p455w0rd") ... The password for the owner's Tesla account

    + Body
    
            user_session%5Bemail%5D=string&user_session%5Bpassword%5D=string

+ Response 302

    + Headers
    
            Set-Cookie: _s_portal_session={cookie}; path=/; secure; HttpOnly
            Set-Cookie: user_credentials=x; path=/; expires=Fri, 03-May-2013 03:01:54 GMT; secure; HttpOnly
            Location: https://portal.vn.teslamotors.com/
            

    + Body
    
            Dummy Welcome Page
            
            
