HOST: http://portal.vn.teslamotors.com

--- Tesla Model S REST API ---
---
This is unofficial documentation of the Tesla Model S REST API used by the iOS and Android apps. It features functionality to monitor and control the Model S remotely. 
---

--
Authentication Flow
These endpoints handle login and session management
--
Returns the login form. Sets a *_s_portal_session* cookie for the session
GET /login
< 200
< Set-Cookie: _s_portal_session={cookie}; path=/; secure; HttpOnly
{
}

Performs the login. Takes in an plain text email and password, matching the owner's login from http://teslamotors.com/mytesla. Note that the JSON data here is just to fit in Apiary's format, but those should be POST variables.

Sets a *user_credentials* cookie that expires in 3 months, which is passed along with all future requests to authenticate the user.

302 redirects back to a dummy welcome page. This page is ignored by the smartphone app and can be ignored by your API client.
POST /login
{
    "user_session[email]": "string",
    "user_session[password]": "string"
}
< 302
< Set-Cookie: _s_portal_session={cookie}; path=/; secure; HttpOnly
< Set-Cookie: user_credentials=x; path=/; expires=Fri, 03-May-2013 03:01:54 GMT; secure; HttpOnly
< Location: https://portal.vn.teslamotors.com/
{
}

--
Vehicle Resource
A logged in user can have multiple vehicles under their account. This resource is primarily responsible for listing the vehicles and the basic details about them.

Must have a *_s_portal_session* and *user_credentials* cookie set for all requests.
--
Retrieve a list of your owned vehicles (includes vehicles not yet shipped!)
GET /vehicles
< 200
< Content-Type: application/json
{
}

--
Vehicle Status Resources
These resources are read-only and determine the state of the vehicle's various sub-systems.

Must have a *_s_portal_session* and *user_credentials* cookie set for all requests.
--
Determines if mobile access to the vehicle is enabled.
GET /vehicles/{id}/mobile_enabled
< 200
< Content-Type: application/json
{
    "reason":"",
    "result":true
}

Returns the state of charge in the battery.
GET /vehicles/{id}/command/charge_state
< 200
< Content-Type: application/json
{
    "charging_state": "Complete",
    "charge_to_max_range": false,
    "max_range_charge_counter": 0,
    "fast_charger_present": false,
    "battery_range": 239.02,
    "est_battery_range": 155.79,
    "ideal_battery_range": 275.09,
    "battery_level": 91,
    "battery_current": 0.0,
    "charge_starting_range": null,
    "charge_starting_soc": null,
    "charger_voltage": 0,
    "charger_pilot_current": 40,
    "charger_actual_current": 0,
    "charger_power": 0,
    "time_to_full_charge": 0.0,
    "charge_rate": -1.0,
    "charge_port_door_open": true
}

Returns the current temperature and climate control state.
GET /vehicles/{id}/command/climate_state
< 200
< Content-Type: application/json
{
    "inside_temp": null,
    "outside_temp": null,
    "driver_temp_setting": 22.6,
    "passenger_temp_setting": 22.6,
    "is_auto_conditioning_on": null,
    "is_front_defroster_on": null,
    "is_rear_defroster_on": false,
    "fan_status": null
}

Returns the driving and position state of the vehicle.
GET /vehicles/{id}/command/drive_state
< 200
< Content-Type: application/json
{
    "shift_state": null,
    "speed": null,
    "latitude": 33.794839,
    "longitude": -84.401593,
    "heading": 4,
    "gps_as_of": 1359863204
}

Returns various information about the GUI settings of the car, such as unit format and range display.
GET /vehicles/{id}/command/gui_settings
< 200
< Content-Type: application/json
{
    "gui_distance_units": "mi/hr",
    "gui_temperature_units": "F",
    "gui_charge_rate_units": "mi/hr",
    "gui_24_hour_time": false,
    "gui_range_display": "Rated"
}

Returns the vehicle's physical state, such as which doors are open.
GET /vehicles/{id}/command/vehicle_state
< 200
< Content-Type: application/json
{
    "df": false,
    "dr": false,
    "pf": false,
    "pr": false,
    "ft": false,
    "rt": false,
    "car_version": "1.19.42",
    "locked": true,
    "sun_roof_installed": true,
    "sun_roof_state": "unknown",
    "sun_roof_percent_open": 0,
    "dark_rims": false,
    "wheel_type": "Base19",
    "has_spoiler": false,
    "roof_color": "None",
    "perf_config": "Base"
}
