HOST: http://portal.vn.teslamotors.com

--- Tesla Model S REST API ---
---
This is unofficial documentation of the Tesla Model S REST API used by the iOS and Android apps. It features functionality to monitor and control the Model S remotely. 
---

--
Authentication Flow
These endpoints handle login and session management
--
Returns the login form. Sets a *_s_portal_session* cookie for the session
GET /login
< 200
< Set-Cookie: _s_portal_session={cookie}; path=/; secure; HttpOnly
{
}

Performs the login. Takes in an plain text email and password, matching the owner's login from http://teslamotors.com/mytesla. 

Sets a *user_credentials* cookie that expires in 3 months, which is passed along with all future requests to authenticate the user.

302 redirects back to a dummy welcome page. This page is ignored by the smartphone app and can be ignored by your API client.
POST /login
{
    "user_session[email]": "string",
    "user_session[password]": "string"
}
< 302
< Set-Cookie: _s_portal_session={cookie}; path=/; secure; HttpOnly
< Set-Cookie: user_credentials=x; path=/; expires=Fri, 03-May-2013 03:01:54 GMT; secure; HttpOnly
< Location: https://portal.vn.teslamotors.com/
{
}

--
Vehicle Resource
A logged in user can have multiple vehicles under their account. This resource is primarily responsible for listing the vehicles and the basic details about them.

Must have a *_s_portal_session* and *user_credentials* cookie set for all requests.
--
Retrieve a list of your owned vehicles (includes vehicles not yet shipped!)
GET /vehicles
< 200
< Content-Type: application/json
{
}

--
Vehicle Status Resources
These resources are read-only and determine the state of the vehicle's various sub-systems.

Must have a *_s_portal_session* and *user_credentials* cookie set for all requests.
--
Determines if mobile access to the vehicle is enabled.
GET /vehicles/{id}/mobile_enabled
< 200
< Content-Type: application/json
{
}

Returns the state of charge in the battery.
GET /vehicles/{id}/command/charge_state
< 200
< Content-Type: application/json
{
}

Returns the current temperature and climate control state.
GET /vehicles/{id}/command/climate_state
< 200
< Content-Type: application/json
{
}

Returns the vehicle's physical state, such as which doors doors open.
GET /vehicles/{id}/command/vehicle_state
< 200
< Content-Type: application/json
{
}

Returns the driving state of the vehicle.
GET /vehicles/{id}/command/drive_state
< 200
< Content-Type: application/json
{
}

Returns various information about the car for the GUI of the smartphone application, such as vehicle color or wheel trim.
GET /vehicles/{id}/command/gui_settings
< 200
< Content-Type: application/json
{
}
